version: "3.8"
services:
  be:
    build: ./be/.
    depends_on:
      - mysql
    command: [ "./wait-for-it.sh","mysql:3306","--","./be/alert-be-linux" ]
    ports:
    - 8899:8899
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=alert
      - MYSQL_USER=alert
      - MYSQL_PASSWORD=123456
    volumes:
      - ./mysql:/var/lib/mysql