// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/echoturing/alert/ent/alerthistory"
	"github.com/echoturing/alert/ent/predicate"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// AlertHistoryQuery is the builder for querying AlertHistory entities.
type AlertHistoryQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.AlertHistory
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (ahq *AlertHistoryQuery) Where(ps ...predicate.AlertHistory) *AlertHistoryQuery {
	ahq.predicates = append(ahq.predicates, ps...)
	return ahq
}

// Limit adds a limit step to the query.
func (ahq *AlertHistoryQuery) Limit(limit int) *AlertHistoryQuery {
	ahq.limit = &limit
	return ahq
}

// Offset adds an offset step to the query.
func (ahq *AlertHistoryQuery) Offset(offset int) *AlertHistoryQuery {
	ahq.offset = &offset
	return ahq
}

// Order adds an order step to the query.
func (ahq *AlertHistoryQuery) Order(o ...OrderFunc) *AlertHistoryQuery {
	ahq.order = append(ahq.order, o...)
	return ahq
}

// First returns the first AlertHistory entity in the query. Returns *NotFoundError when no alerthistory was found.
func (ahq *AlertHistoryQuery) First(ctx context.Context) (*AlertHistory, error) {
	nodes, err := ahq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{alerthistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ahq *AlertHistoryQuery) FirstX(ctx context.Context) *AlertHistory {
	node, err := ahq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AlertHistory id in the query. Returns *NotFoundError when no id was found.
func (ahq *AlertHistoryQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ahq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{alerthistory.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (ahq *AlertHistoryQuery) FirstXID(ctx context.Context) int64 {
	id, err := ahq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only AlertHistory entity in the query, returns an error if not exactly one entity was returned.
func (ahq *AlertHistoryQuery) Only(ctx context.Context) (*AlertHistory, error) {
	nodes, err := ahq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{alerthistory.Label}
	default:
		return nil, &NotSingularError{alerthistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ahq *AlertHistoryQuery) OnlyX(ctx context.Context) *AlertHistory {
	node, err := ahq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID returns the only AlertHistory id in the query, returns an error if not exactly one id was returned.
func (ahq *AlertHistoryQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = ahq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{alerthistory.Label}
	default:
		err = &NotSingularError{alerthistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ahq *AlertHistoryQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := ahq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AlertHistories.
func (ahq *AlertHistoryQuery) All(ctx context.Context) ([]*AlertHistory, error) {
	if err := ahq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ahq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ahq *AlertHistoryQuery) AllX(ctx context.Context) []*AlertHistory {
	nodes, err := ahq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AlertHistory ids.
func (ahq *AlertHistoryQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := ahq.Select(alerthistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ahq *AlertHistoryQuery) IDsX(ctx context.Context) []int64 {
	ids, err := ahq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ahq *AlertHistoryQuery) Count(ctx context.Context) (int, error) {
	if err := ahq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ahq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ahq *AlertHistoryQuery) CountX(ctx context.Context) int {
	count, err := ahq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ahq *AlertHistoryQuery) Exist(ctx context.Context) (bool, error) {
	if err := ahq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ahq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ahq *AlertHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := ahq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ahq *AlertHistoryQuery) Clone() *AlertHistoryQuery {
	return &AlertHistoryQuery{
		config:     ahq.config,
		limit:      ahq.limit,
		offset:     ahq.offset,
		order:      append([]OrderFunc{}, ahq.order...),
		unique:     append([]string{}, ahq.unique...),
		predicates: append([]predicate.AlertHistory{}, ahq.predicates...),
		// clone intermediate query.
		sql:  ahq.sql.Clone(),
		path: ahq.path,
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AlertID int64 `json:"alert_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AlertHistory.Query().
//		GroupBy(alerthistory.FieldAlertID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ahq *AlertHistoryQuery) GroupBy(field string, fields ...string) *AlertHistoryGroupBy {
	group := &AlertHistoryGroupBy{config: ahq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ahq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ahq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		AlertID int64 `json:"alert_id,omitempty"`
//	}
//
//	client.AlertHistory.Query().
//		Select(alerthistory.FieldAlertID).
//		Scan(ctx, &v)
//
func (ahq *AlertHistoryQuery) Select(field string, fields ...string) *AlertHistorySelect {
	selector := &AlertHistorySelect{config: ahq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ahq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ahq.sqlQuery(), nil
	}
	return selector
}

func (ahq *AlertHistoryQuery) prepareQuery(ctx context.Context) error {
	if ahq.path != nil {
		prev, err := ahq.path(ctx)
		if err != nil {
			return err
		}
		ahq.sql = prev
	}
	return nil
}

func (ahq *AlertHistoryQuery) sqlAll(ctx context.Context) ([]*AlertHistory, error) {
	var (
		nodes = []*AlertHistory{}
		_spec = ahq.querySpec()
	)
	_spec.ScanValues = func() []interface{} {
		node := &AlertHistory{config: ahq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, ahq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ahq *AlertHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ahq.querySpec()
	return sqlgraph.CountNodes(ctx, ahq.driver, _spec)
}

func (ahq *AlertHistoryQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ahq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (ahq *AlertHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   alerthistory.Table,
			Columns: alerthistory.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: alerthistory.FieldID,
			},
		},
		From:   ahq.sql,
		Unique: true,
	}
	if ps := ahq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ahq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ahq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ahq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, alerthistory.ValidColumn)
			}
		}
	}
	return _spec
}

func (ahq *AlertHistoryQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(ahq.driver.Dialect())
	t1 := builder.Table(alerthistory.Table)
	selector := builder.Select(t1.Columns(alerthistory.Columns...)...).From(t1)
	if ahq.sql != nil {
		selector = ahq.sql
		selector.Select(selector.Columns(alerthistory.Columns...)...)
	}
	for _, p := range ahq.predicates {
		p(selector)
	}
	for _, p := range ahq.order {
		p(selector, alerthistory.ValidColumn)
	}
	if offset := ahq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ahq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AlertHistoryGroupBy is the builder for group-by AlertHistory entities.
type AlertHistoryGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ahgb *AlertHistoryGroupBy) Aggregate(fns ...AggregateFunc) *AlertHistoryGroupBy {
	ahgb.fns = append(ahgb.fns, fns...)
	return ahgb
}

// Scan applies the group-by query and scan the result into the given value.
func (ahgb *AlertHistoryGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ahgb.path(ctx)
	if err != nil {
		return err
	}
	ahgb.sql = query
	return ahgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ahgb *AlertHistoryGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ahgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (ahgb *AlertHistoryGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ahgb.fields) > 1 {
		return nil, errors.New("ent: AlertHistoryGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ahgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ahgb *AlertHistoryGroupBy) StringsX(ctx context.Context) []string {
	v, err := ahgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (ahgb *AlertHistoryGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ahgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{alerthistory.Label}
	default:
		err = fmt.Errorf("ent: AlertHistoryGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ahgb *AlertHistoryGroupBy) StringX(ctx context.Context) string {
	v, err := ahgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (ahgb *AlertHistoryGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ahgb.fields) > 1 {
		return nil, errors.New("ent: AlertHistoryGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ahgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ahgb *AlertHistoryGroupBy) IntsX(ctx context.Context) []int {
	v, err := ahgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (ahgb *AlertHistoryGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ahgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{alerthistory.Label}
	default:
		err = fmt.Errorf("ent: AlertHistoryGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ahgb *AlertHistoryGroupBy) IntX(ctx context.Context) int {
	v, err := ahgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (ahgb *AlertHistoryGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ahgb.fields) > 1 {
		return nil, errors.New("ent: AlertHistoryGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ahgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ahgb *AlertHistoryGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ahgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (ahgb *AlertHistoryGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ahgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{alerthistory.Label}
	default:
		err = fmt.Errorf("ent: AlertHistoryGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ahgb *AlertHistoryGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ahgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (ahgb *AlertHistoryGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ahgb.fields) > 1 {
		return nil, errors.New("ent: AlertHistoryGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ahgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ahgb *AlertHistoryGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ahgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (ahgb *AlertHistoryGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ahgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{alerthistory.Label}
	default:
		err = fmt.Errorf("ent: AlertHistoryGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ahgb *AlertHistoryGroupBy) BoolX(ctx context.Context) bool {
	v, err := ahgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ahgb *AlertHistoryGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ahgb.fields {
		if !alerthistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ahgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ahgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ahgb *AlertHistoryGroupBy) sqlQuery() *sql.Selector {
	selector := ahgb.sql
	columns := make([]string, 0, len(ahgb.fields)+len(ahgb.fns))
	columns = append(columns, ahgb.fields...)
	for _, fn := range ahgb.fns {
		columns = append(columns, fn(selector, alerthistory.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(ahgb.fields...)
}

// AlertHistorySelect is the builder for select fields of AlertHistory entities.
type AlertHistorySelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (ahs *AlertHistorySelect) Scan(ctx context.Context, v interface{}) error {
	query, err := ahs.path(ctx)
	if err != nil {
		return err
	}
	ahs.sql = query
	return ahs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ahs *AlertHistorySelect) ScanX(ctx context.Context, v interface{}) {
	if err := ahs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (ahs *AlertHistorySelect) Strings(ctx context.Context) ([]string, error) {
	if len(ahs.fields) > 1 {
		return nil, errors.New("ent: AlertHistorySelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ahs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ahs *AlertHistorySelect) StringsX(ctx context.Context) []string {
	v, err := ahs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (ahs *AlertHistorySelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ahs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{alerthistory.Label}
	default:
		err = fmt.Errorf("ent: AlertHistorySelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ahs *AlertHistorySelect) StringX(ctx context.Context) string {
	v, err := ahs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (ahs *AlertHistorySelect) Ints(ctx context.Context) ([]int, error) {
	if len(ahs.fields) > 1 {
		return nil, errors.New("ent: AlertHistorySelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ahs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ahs *AlertHistorySelect) IntsX(ctx context.Context) []int {
	v, err := ahs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (ahs *AlertHistorySelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ahs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{alerthistory.Label}
	default:
		err = fmt.Errorf("ent: AlertHistorySelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ahs *AlertHistorySelect) IntX(ctx context.Context) int {
	v, err := ahs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (ahs *AlertHistorySelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ahs.fields) > 1 {
		return nil, errors.New("ent: AlertHistorySelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ahs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ahs *AlertHistorySelect) Float64sX(ctx context.Context) []float64 {
	v, err := ahs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (ahs *AlertHistorySelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ahs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{alerthistory.Label}
	default:
		err = fmt.Errorf("ent: AlertHistorySelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ahs *AlertHistorySelect) Float64X(ctx context.Context) float64 {
	v, err := ahs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (ahs *AlertHistorySelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ahs.fields) > 1 {
		return nil, errors.New("ent: AlertHistorySelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ahs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ahs *AlertHistorySelect) BoolsX(ctx context.Context) []bool {
	v, err := ahs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (ahs *AlertHistorySelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ahs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{alerthistory.Label}
	default:
		err = fmt.Errorf("ent: AlertHistorySelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ahs *AlertHistorySelect) BoolX(ctx context.Context) bool {
	v, err := ahs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ahs *AlertHistorySelect) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ahs.fields {
		if !alerthistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for selection", f)}
		}
	}
	rows := &sql.Rows{}
	query, args := ahs.sqlQuery().Query()
	if err := ahs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ahs *AlertHistorySelect) sqlQuery() sql.Querier {
	selector := ahs.sql
	selector.Select(selector.Columns(ahs.fields...)...)
	return selector
}
