// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/echoturing/alert/ent/datasource"
	"github.com/echoturing/alert/ent/schema"
	"github.com/facebook/ent/dialect/sql"
)

// Datasource is the model entity for the Datasource schema.
type Datasource struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type schema.DatasourceType `json:"type,omitempty"`
	// Detail holds the value of the "detail" field.
	Detail schema.DatasourceDetail `json:"detail,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Datasource) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},           // id
		&sql.NullString{},          // name
		&sql.NullInt64{},           // type
		&schema.DatasourceDetail{}, // detail
		&sql.NullTime{},            // createdAt
		&sql.NullTime{},            // updatedAt
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Datasource fields.
func (d *Datasource) assignValues(values ...interface{}) error {
	if m, n := len(values), len(datasource.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	d.ID = int64(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		d.Name = value.String
	}
	if value, ok := values[1].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field type", values[1])
	} else if value.Valid {
		d.Type = schema.DatasourceType(value.Int64)
	}
	if value, ok := values[2].(*schema.DatasourceDetail); !ok {
		return fmt.Errorf("unexpected type %T for field detail", values[2])
	} else if value != nil {
		d.Detail = *value
	}
	if value, ok := values[3].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field createdAt", values[3])
	} else if value.Valid {
		d.CreatedAt = value.Time
	}
	if value, ok := values[4].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field updatedAt", values[4])
	} else if value.Valid {
		d.UpdatedAt = value.Time
	}
	return nil
}

// Update returns a builder for updating this Datasource.
// Note that, you need to call Datasource.Unwrap() before calling this method, if this Datasource
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Datasource) Update() *DatasourceUpdateOne {
	return (&DatasourceClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (d *Datasource) Unwrap() *Datasource {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Datasource is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Datasource) String() string {
	var builder strings.Builder
	builder.WriteString("Datasource(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", name=")
	builder.WriteString(d.Name)
	builder.WriteString(", type=")
	builder.WriteString(fmt.Sprintf("%v", d.Type))
	builder.WriteString(", detail=")
	builder.WriteString(fmt.Sprintf("%v", d.Detail))
	builder.WriteString(", createdAt=")
	builder.WriteString(d.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updatedAt=")
	builder.WriteString(d.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Datasources is a parsable slice of Datasource.
type Datasources []*Datasource

func (d Datasources) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
