// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/echoturing/alert/ent/alert"
	"github.com/echoturing/alert/ent/channel"
	"github.com/echoturing/alert/ent/datasource"
	"github.com/echoturing/alert/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	alertFields := schema.Alert{}.Fields()
	_ = alertFields
	// alertDescCreatedAt is the schema descriptor for createdAt field.
	alertDescCreatedAt := alertFields[6].Descriptor()
	// alert.DefaultCreatedAt holds the default value on creation for the createdAt field.
	alert.DefaultCreatedAt = alertDescCreatedAt.Default.(func() time.Time)
	// alertDescUpdatedAt is the schema descriptor for updatedAt field.
	alertDescUpdatedAt := alertFields[7].Descriptor()
	// alert.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	alert.UpdateDefaultUpdatedAt = alertDescUpdatedAt.UpdateDefault.(func() time.Time)
	channelFields := schema.Channel{}.Fields()
	_ = channelFields
	// channelDescCreatedAt is the schema descriptor for createdAt field.
	channelDescCreatedAt := channelFields[4].Descriptor()
	// channel.DefaultCreatedAt holds the default value on creation for the createdAt field.
	channel.DefaultCreatedAt = channelDescCreatedAt.Default.(func() time.Time)
	// channelDescUpdatedAt is the schema descriptor for updatedAt field.
	channelDescUpdatedAt := channelFields[5].Descriptor()
	// channel.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	channel.UpdateDefaultUpdatedAt = channelDescUpdatedAt.UpdateDefault.(func() time.Time)
	datasourceFields := schema.Datasource{}.Fields()
	_ = datasourceFields
	// datasourceDescCreatedAt is the schema descriptor for createdAt field.
	datasourceDescCreatedAt := datasourceFields[4].Descriptor()
	// datasource.DefaultCreatedAt holds the default value on creation for the createdAt field.
	datasource.DefaultCreatedAt = datasourceDescCreatedAt.Default.(func() time.Time)
	// datasourceDescUpdatedAt is the schema descriptor for updatedAt field.
	datasourceDescUpdatedAt := datasourceFields[5].Descriptor()
	// datasource.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	datasource.DefaultUpdatedAt = datasourceDescUpdatedAt.Default.(func() time.Time)
	// datasource.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	datasource.UpdateDefaultUpdatedAt = datasourceDescUpdatedAt.UpdateDefault.(func() time.Time)
}
