// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Alert is the predicate function for alert builders.
type Alert func(*sql.Selector)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// Datasource is the predicate function for datasource builders.
type Datasource func(*sql.Selector)
